SELECT USER_ID ,NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN USED_GOODS_BOARD UGB ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
